apiVersion: v1
kind: pod
metadata:
  name: pod-demo-storage
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx
      volumeMount:
        - name: html
          mountPath: /usr/share/nginx/html
    - name: debug
      image: rkalluru/learnk8s:rhel9-bare
      volumeMount:
        - name: html
          mountPath: /mnt