apiVersion: v1
kind: ReplicaSet
metadata:
  name: test01
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: test01
  template:
    metadata:
      labels:
        tier: test01
    spec:
      containers:
        - name: nginx
          image: nginx
