apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "500Mi"
        cpu: "10m"
      limits:
        memory: "6100Mi"
        cpu: "200m"
