apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "4000Mi"
        cpu: "100m"
      limits:
        memory: "5100Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "4000Mi"
        cpu: "100m"
      limits:
        memory: "5100Mi"
        cpu: "200m"
