apiVersion: apps/v1
kind: Deployment
metadata:
  name: constraint-sample
  labels:
    app: default
spec:
  replicas: 12
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
  spec:
    topologySpreadConstraints:
      - topologyKey: topology.kubernetes.io/zone
        maxshew: 1
        whenUnSatifiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: default
    containers:
      - name: nginx
        image: nginx:latest